name: shell commands 
on: [push]
jobs:
  run-shell-command:
    runs-on: test-pod
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: Find current dir
        run: |
          pwd
          ls -la
      - name: echo a string
        run: echo "Hello World"
      - name: multi line script
        run: |
          node -v
          npm -v
